insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('Kurtka Softshell trekkingowa - TREK 500 WINDWARM', 200, 'FEMALE', 'YEAR_ROUND', 'JACKETS', 'https://www.decathlon.pl/p/kurtka-softshell-trekkingowa-trek-500-windwarm-damska/_/R-p-126146', 'softW', 'Uniwersalna kurtka softshell. Suwaki wentylacyjne, otwory na kciuk, gumka w pasie i 2 kieszenie boczne.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('Softshell trekkingowy - TREK 900 WIND', 150, 'MALE', 'YEAR_ROUND', 'JACKETS', 'https://www.decathlon.pl/p/softshell-trekkingowy-trek-900-wind-m-ski/_/R-p-134865', 'softM', 'Idealna dodatkowa ochrona przed wiatrem.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('Black Diamond Cirque Shell', 700, 'FEMALE', 'SPRING_AUTUMN', 'JACKETS', 'https://taternik-sklep.pl/kurtka-damska-black-diamond-cirque-shell.html', 'softW2', 'Damski wiatroodporny softshell zapewnia solidną ochronę przed wiatrem od wiosny aż po jesień.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('Kurtka Black Diamond Dawn Patrol Shell', 760, 'MALE', 'YEAR_ROUND', 'JACKETS', 'https://taternik-sklep.pl/kurtka-black-diamond-dawn-patrol-shell.html', 'softM2', 'Ta świetnie oddychająca, elastyczna kurtka to cienki, wiatroszczelny softshell o technicznym kroju.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('Spodnie turystyczne - SH500 x-Warm - stretch', 170, 'MALE', 'WINTER', 'PANTS', 'https://www.decathlon.pl/p/spodnie-turystyczne-sh500-x-warm-stretch-m-skie/_/R-p-193598?mc=8493789&c=Czarny', 'pantsM', 'Ciepłe, hydrofobowe, wiatroodporne, idealne na wędrówki po śniegu.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('Spodnie turystyczne 2w1 - TREK 500', 170, 'MALE', 'SPRING_AUTUMN', 'PANTS', 'https://www.decathlon.pl/p/spodnie-trekkingowe-2w1-trek-500-m-skie/_/R-p-192275', 'pantsM2', 'Spodnie 2 w 1 przekształcane w krótkie spodenki.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('Spodnie turystyczne SH500 x-Warm stretch', 170, 'FEMALE', 'WINTER', 'PANTS', 'https://www.decathlon.pl/p/spodnie-turystyczne-sh500-x-warm-stretch-damskie/_/R-p-193593', 'pantsW', 'Ciepłe, hydrofobowe, wiatroodporne, idealne na wędrówki po śniegu.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('Spodnie trekkingowe 2w1 TREK 500', 170, 'FEMALE', 'SPRING_AUTUMN', 'PANTS', 'https://www.decathlon.pl/p/spodnie-trekkingowe-2w1-trek-500-damskie/_/R-p-192297', 'pantsW2', 'Rozciągliwa tkanina: maksymalny komfort. Wstawki z oddychającej tkaniny w strefach narażonych na przetarcia.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('Polar turystyczny SH500 x-warm', 170, 'FEMALE', 'WINTER', 'FLEECES_SWEATSHIRTS', 'https://www.decathlon.pl/p/polar-turystyczny-sh500-x-warm-damski/_/R-p-305155', 'fleeceW1', 'Bluza polarowa idealna na wędrówki w zimne dni. Wstawki z rozciągliwego materiału po bokach zapewniają swobodę ruchów.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('Polar turystyczny - MH120 - damski', 50, 'FEMALE', 'SPRING_AUTUMN', 'FLEECES_SWEATSHIRTS', 'https://www.decathlon.pl/p/polar-turystyczny-mh120-damski/_/R-p-302556', 'fleeceW2', 'Ciepły i lekki. Materiał z recyklingu. Idealny mikropolar na dno plecaka.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('Polar turystyczny MH120', 50, 'MALE', 'SPRING_AUTUMN', 'FLEECES_SWEATSHIRTS', 'https://www.decathlon.pl/p/polar-turystyczny-mh120-m-ski/_/R-p-176453', 'fleeceM1', 'Ciepły i lekki, izolujący przed zimnem w górach. Niezbędny na dno plecaka.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('Polar turystyczny - SH500 x-Warm', 170, 'MALE', 'WINTER', 'FLEECES_SWEATSHIRTS', 'https://www.decathlon.pl/p/polar-turystyczny-sh500-x-warm-m-ski/_/R-p-304985', 'fleeceM2', 'Przeznaczony na wędrówki w zimne dni. Wentylacje i elastyczne wstawki zapewniają dobry komfort termiczny.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('Bluza Columbia Coggin Peak FZ Hooded Fleece', 250, 'FEMALE', 'SPRING_AUTUMN', 'FLEECES_SWEATSHIRTS', 'https://taternik-sklep.pl/bluza-damska-columbia-coggin-peak-fz-hooded-fleece.html', 'fleeceW3', 'Doskonale spisze się zarówno jako odzież wierzchnia na letnie poranki, jak i warstwa pośrednia pod kurtkę turystyczną!');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('Bluza Arc teryx Remige Hoody', 260, 'MALE', 'SUMMER', 'FLEECES_SWEATSHIRTS', 'https://taternik-sklep.pl/bluza-arc-teryx-remige-hoody.html', 'fleeceM3', 'Bardzo lekka, oddychająca, wyposażona w materiał chroniący przed UV.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('Columbia Heather Canyon Softshell', 400, 'FEMALE', 'SPRING_AUTUMN', 'JACKETS', 'https://8a.pl/softshell-damski-columbia-heather-canyon-softshell-nocturnal', 'softW8a','Lekkość niezbędna na hikingu oraz ochrona przed wiatrem, której potrzebujesz zawsze.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('Kurtka trekkingowa - Trek 100 kaptur', 150, 'FEMALE', 'WINTER', 'JACKETS', 'https://www.decathlon.pl/p/kurtka-trekkingowa-trek-100-damska/_/R-p-312532', 'jacketW', 'Cienka i ciepła. Najbardziej ekologiczna z zimowych kurtek trekkingowych na wyprawy w góry!');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('Kurtka trekkingowa puchowa TREK 900', 250, 'MALE', 'WINTER', 'JACKETS', 'https://www.decathlon.pl/p/kurtka-turystyczna-zimowa-forclaz-700-meska/_/R-p-12077', 'jacketM', 'Bardzo ciepła, lekka, kompresyjna 100% puch/pierze. Idealna jako 2. warstwa.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('Kurtka Softshell trekkingowa - TREK 100 WINDWARM', 120, 'MALE', 'SPRING_AUTUMN', 'JACKETS', 'https://www.decathlon.pl/p/kurtka-softshell-trekkingowa-trek-100-windwarm-meska/_/R-p-121928?mc=8343858&c=Czarny', 'jacketMSoft', 'Uniwersalna, idealna na zmieniające się warunki pogodowe.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('Kurtka trekkingowa puchowa TREK 500 kaptur', 180, 'MALE', 'WINTER', 'JACKETS', 'https://www.decathlon.pl/p/kurtka-trekkingowa-puchowa-trek-500-kaptur-meska/_/R-p-306570?mc=8587339&c=Ochra_Be%25C5%25BCowy', 'jacketMw', 'Kurtka z wypełnieniem z grubej watoliny na wyprawy trekkingowe w zimne dni (przy temp. do -10°C).');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('Kurtka trekkingowa puchowa TREK 900', 400, 'FEMALE', 'WINTER', 'JACKETS', 'https://www.decathlon.pl/p/kurtka-puchowa-turystyczna-top-warm-damska/_/R-p-144205?mc=8502893&c=Purpurowy','jacketWw', 'Bardzo ciepła i lekka kurtka na duże mrozy. Doskonała izolacja, ochrona przed zimnem, wypełnienie puchowe, ochronny kołnierz.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('Kurtka Salewa Pelmo Convertible', 700, 'MALE', 'YEAR_ROUND', 'JACKETS', 'https://www.polarsport.pl/odzie/kurtki/kurtki-3in1/kurtka-salewa-pelmo-convertible.html', 'jacketMsa', 'Wszechstronna, wodoodporna kurtka trekkingowa z wygodnym polarem zapinanym na zamek.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('Kurtka Salewa Pelmo Convertible', 700, 'FEMALE', 'YEAR_ROUND', 'JACKETS', 'https://www.polarsport.pl/odzie/kurtki/kurtki-3in1/kurtka-salewa-pelmo-convertible-women-s.html', 'jacketWsa', 'Wszechstronna, wodoodporna kurtka trekkingowa z wygodnym polarem zapinanym na zamek.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('The North Face Apex Nimble', 320, 'FEMALE', 'SPRING_AUTUMN', 'JACKETS', 'https://www.polarsport.pl/odzie/kurtki/kurtki-nieprzewiewne/kurtka-the-north-face-apex-nimble-women-s.html', 'jacketWno', 'Apex Nimble to idealny wybór na trekking podczas chłodniejszej pogody.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('Kurtka Monica softshell', 200, 'MALE', 'SUMMER', 'JACKETS', 'https://alpin.pl/produkty/ona/odziez-damska/kurtki/fourelements-01-l-kurtka-monica-softshell.html', 'jacketWmonica', 'Damski, bezmembranowy softshell idealnie na wietrzne dni.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('Kurtka Stratos Mount X', 150, 'MALE', 'YEAR_ROUND', 'JACKETS', 'https://alpin.pl/produkty/on/odziez-meska/kurtki/mountx-12-s-kurtka-stratos-mount-x.html', 'jacketMstratos', 'Stratos jest całoroczną kurtką, tzw. parka, do której można podpiąć polar w zimniejsze dni. Idealna na wycieczki górskie.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('Kurtka MOUNTAIN EQUIPMENT AEROFOIL FULL ZIP', 470, 'MALE', 'SUMMER', 'JACKETS', 'https://www.polarsport.pl/odzie/kurtki/kurtki-nieprzewiewne/kurtka%20mountain%20equipment%20aerofoil%20full%20zip.html', 'jacketMyellow', 'Niezwykle lekka, odporna na działanie wiatru i wilgoci.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('SPODNIE MĘSKIE TRIMM MOTION', 260, 'MALE', 'SPRING_AUTUMN', 'PANTS', 'https://sklepgorski.pl/spodnie-meskie-trimm-motion', 'pantMtrimm', 'Męskie spodnie softshellowe renomowanej czeskiej marki Trimm.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('SPODNIE DAMSKIE RAB VECTOR', 200, 'FEMALE', 'SPRING_AUTUMN', 'PANTS', 'https://sklepgorski.pl/softshellowe-spodnie-damskie-rab-vector', 'pantWrab', 'Proste spodnie trekkingowe gwarantujące ochronę w niesprzyjających warunkach. Wodoodporne, wiatroszczelne i bardzo wytrzymałe.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('SPODNIE TREKKINGOWE DAMSKIE BERGANS OF NORWAY UTNE ZIPOFF', 400, 'FEMALE', 'SPRING_AUTUMN', 'PANTS', 'https://sklepgorski.pl/spodnie-trekkingowe-damskie-bergans-of-norway-utne-zipoff.html', 'pantWbergans', 'Bardzo uniwersalne spodnie trekkingowe, które w jednej chwili można przekształcić w szorty.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('KALESONY DAMSKIE LASTING ATAKA', 180, 'FEMALE', 'WINTER', 'THERMOACTIVE_UNDERWEAR', 'https://sklepgorski.pl/kalesony-damskie-lasting-ataka-100-merino.html', 'thermoWataka', 'Wykonane w 100% z wełny merynosa o gramaturze 160g, która posiada unikalną zdolność termoregulacji.');
insert into PRODUCTS (NAME, PRICE, PRODUCT_GENDER, SEASON, CATEGORY, LINK, PICTURE_NAME, DESCRIPTION) values ('Softshell Viking Maroni Lady', 200, 'FEMALE', 'SPRING_AUTUMN', 'JACKETS', 'https://opensport.pl/viking-damska-kurtka-softshell-viking-maroni-lady-730-22-8800-19-granatowy-s,c274,p25861,24170da903bf04274,pl.html?gclid=Cj0KCQjwyZmEBhCpARIsALIzmnL5mrAWyOQsn0N-V8Y8Yq-iVekowfe9-v_DZqcCYUUspGsyfZ26BeAaAqjLEALw_wcB', 'jacketWviking', 'Wnętrze kaptura i kurtki z mikropolaru. Lekka, wygodna i oddychająca, ale przy tym zapewniająca ochronę przed wiatrem i deszczem.');





