insert into CATEGORIES (NAME) values ('jackets');
insert into CATEGORIES (NAME) values ('pants');
insert into CATEGORIES (NAME) values ('fleeces/sweatshirts');
insert into CATEGORIES (NAME) values ('thermoactive underwear');
insert into CATEGORIES (NAME) values ('shoes');
insert into CATEGORIES (NAME) values ('socks');
insert into CATEGORIES (NAME) values ('gloves');
insert into CATEGORIES (NAME) values ('hats');
insert into CATEGORIES (NAME) values ('gaiters');
insert into CATEGORIES (NAME) values ('backpacks');